### ISSUE TITLE
1.12.2 fork

### ISSUE THREAD

**Issue by diprotic** [TheGreyGhost/SpeedyTools#2]
The issues is that there isn't a version for the latest. Can you please port it?

**Comment by TheGreyGhost** [comment]
Hi diprotic
Sorry, I stopped updating this mod a couple of years ago now.  There were such major changes to the world code that I would've needed to rewrite much of it from scratch, and unfortunately I don't have as much free time as I used to...  Sorry :(

Cheers
  TGG
