### ISSUE TITLE
1.12.2 - 2018 update

### ISSUE THREAD

**Issue by diprotic** [TheGreyGhost/SpeedyTools#3]
I know you said you let the mod/project die especially due to a time factor but TGG there is zero mods out here that do what your mod did. There's just a bunch of mods that do one thing and they do it terribly. On top of that there are zero mods that have a transoccultion feature (I think that's what you called it), copy/paste mods are terrible and very limited. The only other mod out here that even comes close to yours is worldedit and even then it's a horrible mc experience imho. Anyway I can convince you to please port it?

**Comment by TheGreyGhost** [comment]
Howdy 
Thanks for the feedback :)
I'd for sure like to, unfortunately I just don't have the free time I did three years ago when I wrote it originally.  It would be months of work that I need to spend on other things not computer-related.

You might be able to convince another modder to update it, but it would be hard going cause most folks prefer to work on their own stuff....

Cheers
  TGG

**Comment by kekefreedog** [comment]
Since Claude Code came out, I am  trying to adapt the code to a more recent version of Minecraft hehe 🤖
